### ISSUE TITLE
Training speed

### ISSUE THREAD

**Issue by Inferencer** [XChenZ/havatar#1]
What would I expect the average time training a model to take using this project?
I know it's dependent on GPU etc but would like an idea regardless

By the way your team is doing great work I'm looking forward to any possible Gaussian head projects you might have upcoming.

**Comment by XChenZ** [comment]
In our implementation, with one 3090 GPU, two-stage training costs at least one day.

Thanks for your interest in our team! You can follow other two upcoming gaussian-avatar related works: 
https://github.com/YuelangX/Gaussian-Head-Avatar
https://github.com/lizhe00/AnimatableGaussians
