### ISSUE TITLE
environment.yaml

### ISSUE THREAD

**Issue by mp3pintyo** [XChenZ/havatar#4]
Hello!

Windows WSL
In the pip section of the environment.yaml file, this package is wrong:
- fused==0.0.0
The available version of this is:
- fused==0.1.0

Error 2:
- pytorch3d==0.6.0

https://pypi.org/project/pytorch3d/#history

Thanks for fixing it.

**Comment by XChenZ** [comment]
Thanks for your correction! Actually, these two packages are locally compiled at that time. For pytorch3d, I think recent newer version is also suitable.

**Comment by Inferencer** [comment]
> Hello!
> 
> Windows WSL In the pip section of the environment.yaml file, this package is wrong:
> 
>     * fused==0.0.0
>       The available version of this is:
> 
>     * fused==0.1.0
> 
> 
> Error 2:
> 
>     * pytorch3d==0.6.0
> 
> 
> https://pypi.org/project/pytorch3d/#history
> 
> Thanks for fixing it.

can you share your env.yaml for windows, i'm having a little trouble with some of it
