### ISSUE TITLE
how about the gpu requirement?

### ISSUE THREAD

**Issue by ZhenyanSun** [XChenZ/havatar#6]
I meet the cuda out of memeory issue. torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 23.50 GiB of which 35.69 MiB is free. Process 210694 has 22.70 GiB memory in use. Including non-PyTorch memory, this process has 768.00 MiB memory in use. Of the allocated memory 509.71 MiB is allocated by PyTorch, and 34.29 MiB is reserved by PyTorch but unallocated.

Is this reasonable?

**Comment by XChenZ** [comment]
I conducted experiments on a single RTX3090 GPT. The first stage training costs little GPU ( less than 10G). The second stage training costs about 22G with batchsize=2.

**Comment by ZhenyanSun** [comment]
thx

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: XChenZ ***@***.***>
发送时间: Monday, March 4, 2024 10:19:31 AM
收件人: XChenZ/havatar ***@***.***>
抄送: ZhenyanSun ***@***.***>; Author ***@***.***>
主题: Re: [XChenZ/havatar] how about the gpu requirement? (Issue #6)


I conducted experiments on a single RTX3090 GPT. The first stage training costs little GPU ( less than 10G). The second stage training costs about 22G with batchsize=2.

―
