### ISSUE TITLE
Changing Rendering Viewing Angle

### ISSUE THREAD

**Issue by KaneLindsay** [XChenZ/havatar#7]
How can I modify the viewing angle from front-center for rendering?

**Comment by XChenZ** [comment]
You can change the view_num for free-view rendering.
https://github.com/XChenZ/havatar/blob/98b3fe53b6191a643da085d46e7c1cf9429934d2/data_preprocessing/fit_video.py#L421C5-L421C29

If you want to render with a fixed viewpoint, you could fix the angle here (https://github.com/XChenZ/havatar/blob/98b3fe53b6191a643da085d46e7c1cf9429934d2/data_preprocessing/fit_video.py#L457)
